travis:
  secure:
    BINSTAR_TOKEN: DvXd/aU1gP7+Wzlom06ZGvYmNni+8TqTZXvVI+58LQ/mnTyDZlbeUYQRLmZ6762gM9YO2c4f0+BbFESf/I9eQDbXVZfcEliNGst8HazwelaPYWEG3h++npJmfX5z79G37rhH85BW7lCO72dS1IWTKGda1AWipBr/ehw7QipvGCiBe2QS4uM25KDXkmu54VXf3nVOIiwlnN+EksBg9Oo8aK+V4sdZfKTelagNm62gB8Pxig+lMeZVjz0EZwC9MU7mxtnQuveje59CHTIAK0OHyhhztBUoVXweWDjg41RfQXhkpd9zJKf0jMJ/SkXBXsk+nifKsxAGCyBKreBy7d7C92sy4uTeQ9ztOXWDB9DKsSq0G0LAadSp64c/xyv7dUkuSUPcFgEr+3ELxVwjB1WkMusmND4iZ8x7DpHdisuDjlpMzc1xmz0yfE9Kh5VKRAuJhDeN77E0SyY7N8fZaT5xYp25y9UFvtY2tNJOYkiQPrd+xjSmuqqyX0Y0jsSkFmHuSNji4HjmfsoCO0RJJSiV0f4xAmhK9lC2iEJpQ84MJxrizCC8sg3kPMFvmbxMFQwdwWynAJQcPyM7KMoDXLAOPSc1pBdoXvVXvbbuDpgjBedlhcynJwOF3sN/7JkpkndXMvVxMR9fryK1MB7FIDwkHn/zpbsRkHhL95fZRl/sVdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
